### ISSUE TITLE
Framework error

### ISSUE THREAD

**Issue by vdecree** [HashandSalt/NPMboilerplate#1]
Hi there,

I came across this and was really interested in seeing if I can survive without Gulp. I have this setup on OSX and I am trying to pull in some frameworks I use like so:

```
"frameworkpath": ["node_modules/susy/sass", "node_modules/breakpoint-sass/stylesheets", "node_modules/modularscale-sass/stylesheets"]
```

And in my sass file:
```
// import npm modules
@import "susy";
@import "modular-scale";
@import "breakpoints";
```

But I am getting errors:

```
yarn start
yarn run v1.1.0
$ yarn clean:assets && yarn build
{
  "status": 1,
  "file": "/Users/mathewdoidge/www/mortise/src/sass/site.scss",
  "line": 2,
  "column": 1,
  "message": "File to import not found or unreadable: susy.\nParent style sheet: /Users/mathewdoidge/www/mortise/src/sass/site.scss",
  "formatted": "Error: File to import not found or unreadable: susy.\n       Parent style sheet: /Users/mathewdoidge/www/mortise/src/sass/site.scss\n        on line 2 of src/sass/site.scss\n>> @import \"susy\";\n   ^\n"
}
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
If I look at my `node_modules`, I can see susy and the other frameworks are there, so is my use of an array of paths for `frameworkpath` illegal?

**Comment by HashandSalt** [comment]
Hey @vdecree Sorry for the late reply.... to be brutally honest, we didnt try it with multiple frameworks. Did you solve it?

You can feed multiple load paths to Node SASS, so would need a couple more vars to store the paths


`node-sass sass/ --include-path /1 --include-path /2`
